# Generated by Django 5.2.5 on 2025-08-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowmodel',
            name='borrow_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='borrowmodel',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrowmodel',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
