# Generated by Django 5.2.5 on 2025-08-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0003_alter_borrowmodel_borrow_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowmodel',
            name='borrow_date',
            field=models.DateField(),
        ),
    ]
