# Generated by Django 5.2.5 on 2025-08-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0004_alter_borrowmodel_borrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowmodel',
            name='borrow_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
